- id: reformat-gherkin
  name: reformat-gherkin
  description: 'Reformat Gherkin documents'
  entry: reformat-gherkin
  language: python
  language_version: python3
  require_serial: true
  files: "\\.(feature)$"
