update: insecure
branch: develop
schedule: "every week"
requirements:
  - requirements.txt:
      update: all
      pin: True
  - requirements-dev.txt:
      update: False
      pin: False
branch_prefix: pyup/
