language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
env:
  global:
    - secure: AaLOyW4l/ryzd3X3mLoOorg48KzD0uODLVglU36a8bQNEqQKMDl8ExVcEcyzGTcM77Ap3777Y+Mu4czjlft2VqOpR9J9cPI2XpKlZ01RfNdUWD0jPy0m0PnVVguf7D541JAgwym9SO1LNF0cX5dpitMMN+6YZguXrm4mP3tY79cVAkK4uF8W91kYGEGNVIdWC8iTZxzBMzJYj9fVHIRYUZ6w720kwjg5HYVcQgswbeKKptO1Xs036frjRk1b6NBnmd+xnxT3C7SGzYFNCEqzYL4QEzqLKTehkbYxUp4hai+1NUa5vgqVgSPL15BgyL+mDsvO0zcOSjoOR91rPgEEWaZj+/VJxiX5hVozhT2oktKx9uGIwHMAJmXgTKOmyKylYY4Vhmk7g2jVswDhFgW0sRrNVo3ho458gwOz+Lw4hmxMabYVR8Y18NR7baaGWwTeG5kgBmswsf0a1f65kJIxpxkwoMi2taG/F0RYUljKZ8YQtlitsn9wW0no8RAT/EHzfgpaIlsPKhIsGAVBFk9IOR0W9dAdJrGHlo8pnUW3ZTa0TfhYLM8FG2THyo/uz3YgXbNo5RO6bFHMH6q7gkwwDmj2eN27iMTq4D1WvhtKcDQ2fj6WOkvLNu1VcA/fbdNEg3I4dNQQld502f9HjypS6HkyQzPqS+Epp8HTKZpa5jk=
    - secure: OWOtHde6Uj9Frhz9oKO9TTFHrmhl7DYoI5KjSjPLDUjF0nGRztEVH0IzyVLXpbvtp1V8oAoKbyWgbTvVV2Yu5FJ7pr/4MKSS1AHCL3DtvE7QGdEBEYCeGrHxelIqgFOaGtL7+gXttPQyI8HAxaYSL2ubyk9vZXofuzL6cUOG67Tw/GO5Qo66qHhHE/9A8LI4jPatCPK1BDUPJ3Beldwv5BnfugW3CXRXfT1zPneKDyCtk75Dx/3a0bOnDCfd6fyMsTPNjaz6RiNginAGBn+U9NfO1WHRb3gaxI+8ulOAWdckYJ9OrTeKoAwCFtnm/iIE+g087uH8zPadbSWEbU+iGnzjTkP1UzDNJGaeX7QYun2kpBDNSbCRJJ9uigQJ3A+ejBOMOjf89HT4Hun41l5VvHqMrw9r+oLJUxuCDO3CEu4lOxQ3S92suIiy/L3tr92XV9uB+GOmPoq9g6cghbq7NEb7M+ChsynN3zDVcO1Kt2TYa+kfRzEo3bi7NARKSYlGHfCOeY29DfNtLGhrY7rn9XToOtDKuqonXV9iX5LE5L6v5Pwtl5fwoW+184Uu3vaFywmFdQIeGUVnVnMm1060LOkLBt7Csxcav6DfaesCgmUDFnrUlIFZE31m+yAhwZ0IMaeuyTNGxzr0z9kShmVgMzj8Opqpz2gzmcFbRDzjq7M=
install:
  - pip install poetry
  - poetry install
  - pip install flake8 coveralls
script:
  - flake8
  - pytest --cov=reformat_gherkin/
after_success:
  - coveralls
before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master
    python: "3.7"
