language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install poetry
  - poetry install
  - pip install flake8 coveralls
script:
  - flake8
  - pytest --cov=reformat_gherkin/
after_success:
  - coveralls
