language: python
dist: xenial
python:
  - "3.7"
  - "3.8"
  - "3.9"
jobs:
  include:
    - python: "3.7"
      env:
        - JOB=linting
      install:
        - pip install pre-commit
        - pre-commit install
      script:
        - pre-commit run --all-files
env:
  global:
    - secure: UYrFiynXTsYj9BfjY3scnI8E1f+j721RzHGf/jXoUJIgs7QGW7hN5sRbmdm8u57SY1cs+HHV36R6wOIvI3/7cm+wbugWt31fqCwbynaNdIbBkNu0hkZuOMJv63I8OcD/HDELsrtCTA1OtWaZU27CvnmIbIhmRYvIUVwA6MQrShGH6Lc68ST6yhBb+z8I2IMEv/C2Tx2CbzIJsxUJVSvurwgzvH3vS1M0z4f4cpDQLimZaa81GKkisq9gEzDzOmpK3Bj/zryrI7ZXO+4V9CXFuH0b6YXZOob/GzXw73jlOYoh3Q4z8A7qvgVw+Tk+PsVds26c7l5mdkX8iHTVWqZm5EouEkaVowm8SloHl0HA32bNxvN/t5pGmghgwOMTJrbwoMdBIt0gOUg+Na2R9u9M3G7D/t2KDSF6uthT4uwbJrlSZpKFcWZE75Nr6xGKrI7o/uzQShAA2oay9H3bkibTdp6Zcxl6C/RVVMTYPH2gyLDgNl6m8ZFKq0I4ENyYmGkTPWVzcBgetNKU0sjPCJnpnrbez+14dWJTYJ6SEa/1yLzIKCzmZpk4NV7aXrZkOCqc8Cq3hmMWIVV8TUpdARxlIoMj5TP+a41IWhQfVf6cuvwN6wN8NpfT3NzcwI5tLwTlpnRA1xsv7wIUDqceRKaZEh0K+cpZ1PO1W93aLKLgrvs=
    - secure: VCvqWiuboVrj8T+E0l6ywYZicz+EWr0pc5XKVut59fyvbv4wCkM6E+QowfR/tonbm9IEEUpC0KAWyLKlaNB1Cibc78Ql2RZAOnL5B0hrLNk+2gRq4S6OgAkw1Gs0drZ6FcO0spiYmLsby/wWXOb8iy/xROEXjV7QHQpNhbgpiHmDKKMwyp6II6Q6B6ododEkobkcaKO2Cnn3xsur8MXRQIWVYcd7zIH7oje9zZLtgSORTUXiDRTc3K/i671PW6JcL3baHCKohQku/ePdQEzJJ7sEHSOuURBGTB3Hx6OiqGMX86ZYFej46xbVx9Gv9He4z97EFR4GUPBojfsj+MCiGIHxFc3ASsy1MBeJ/uvfQwx3MtIfTSG3fCF7pjj3RpldYIcUk5mxCNYSJsQvEsJ2jwQw++G/+TvJ8JjRvBb+w1iSmyLtxPyR+/sqHnEVjTQ6QAVSRASMyR+uL1+BpGwhN+8IdJzvm3w+Fe952W8/oZt8B5Gd/yu3uBzt31qDxxLOwb+jBPvZ+12AaCnvL1xVQcEYtJf/sqNzk+1m4Wb9AHq34Rqc4Z1ZnDVyBna8r0oDtBs991IOgSNir4pwEf43sSSSs2/ytgN2jMwQ9pe+gfugHKcUmspiDW9K/3HJR0rf/OJrj8aBj+eTmnO3+7FiAzQwgF71V4Jycu1KdHHqN0A=
install:
  - pip install poetry
  - poetry install
  - pip install coveralls
script:
  - pytest --cov=reformat_gherkin/
after_success:
  - coveralls
before_deploy:
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master
    python: "3.8"
