language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install flake8 coveralls
script:
  - flake8
  - pytest --cov=reformat_gherkin/
after_success:
  - coveralls
