jobs:
  - template: .azure-pipelines-templates/jobs.yml
    parameters:
      pythonVersions:
        - '3.6'
        - '3.7'
        - '3.8'
      images:
        - 'ubuntu-latest'
        - 'macOS-latest'
        - 'windows-latest'
