[tool.poetry]
name = "reformat-gherkin"
version = "0.1.0"
description = "Formatter for gherkin language"
authors = ["Duc-Minh Phan <alephvn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
gherkin-official = "^4.1"

[tool.poetry.dev-dependencies]
pre-commit = "^1.14"
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
